### ISSUE TITLE
Remove `poetry-export-plugin` from PyPI

### ISSUE THREAD

**Issue by nzig** [python-poetry/poetry-plugin-export#114]
PyPI has both
https://pypi.org/project/poetry-export-plugin/
and 
https://pypi.org/project/poetry-plugin-export/

The second is the new one, but the first is almost identical except that it's older. `poetry-export-plugin` is the first result in Google for "poetry-plugin-export pypi", which caused me some confusion.

If possible, could you have this package removed? If not, please add a deprecation warning with a link to `poetry-plugin-export` on PyPI.

Thanks!

**Comment by neersighted** [comment]
Tagging @sdispater as he is the sole PyPI maintainer of that package.

**Comment by sdispater** [comment]
https://pypi.org/project/poetry-export-plugin/ has been removed from PyPI.
