### ISSUE TITLE
Exporter expects instance of cleo.io.io.IO

### ISSUE THREAD

**Issue by isaacbrodsky** [python-poetry/poetry-plugin-export#116]
In https://github.com/python-poetry/poetry-plugin-export/blob/main/src/poetry_plugin_export/exporter.py#L188, the exporter checks against `cleo.io.io.IO`. It looks like this could be replaced with an appropriate class from the Python `io` module to make it easier for consumers to write the output to a buffer (i.e. a `StringIO`)

**Comment by neersighted** [comment]
`cleo.io.io.IO` is not a type that is compatible with standard library IO -- it is a high-level representation of text IO to allow for testablity through dependency injection. 

While we've never discussed it, I don't think it's the intent of this codebase to be consumed through anything but the CLI. Certainly, if you're missing functionality, MRs here would benefit all users, and given the plugin API in Poetry is still experimental and maturing, I doubt we can commit to stable internals for this plugin in the short run, if we do determine such a thing to be desirable.
