### ISSUE TITLE
Possible regression with duplicating dependency with extra

### ISSUE THREAD

**Issue by tnydg99** [python-poetry/poetry-plugin-export#129]
- **Poetry version**: 1.2.1
- **Python version**: 3.8.9
- **OS version and name**: macOS 12.6
- **pyproject.toml**: https://gist.github.com/tnydg99/0b018320ae7d2a6600a81f9d2d04d92c

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When using v1.2.x of Poetry, the export command seems to be duplicating the same dependency, but with lines containing extras and lines not containing extras in the output requirements.txt file. In this example, google-api-core is one that is duplicate with both `google-api-core` and `google-api-core[grpc]`. This happens with or without including hashes. This is behavior specific to v1.2.x, as 1.1.x (up to latest release of 1.1.15) does not replicate this behavior.

Attached comparable requirements.txt files

[requirements_115.txt](https://github.com/python-poetry/poetry-plugin-export/files/9687532/requirements_115.txt)
[requirements_121.txt](https://github.com/python-poetry/poetry-plugin-export/files/9687536/requirements_121.txt)

**Comment by dimbleby** [comment]
Not a bug, https://github.com/python-poetry/poetry/pull/5688#issuecomment-1137845130

**Comment by tnydg99** [comment]
> Not a bug, [python-poetry/poetry#5688 (comment)](https://github.com/python-poetry/poetry/pull/5688#issuecomment-1137845130)

@dimbleby I just want to make sure I understand the comment, but in python-poetry/poetry#5688, the markers were different and having two different lines made sense. But in this case, the markers are the exact same.

```
google-api-core==2.10.1 ; python_full_version >= "3.7.3" and python_version < "3.10"
google-api-core[grpc]==2.10.1 ; python_full_version >= "3.7.3" and python_version < "3.10"
```

Based on these being the same markers, is this still the correct behavior?

**Comment by dimbleby** [comment]
arguably this could be deduplicated down to just `google-api-core[grpc]` but I know of no reason to care about this.

Are you seeing an actual problem or is this just a question about cosmetics?

**Comment by tnydg99** [comment]
I am seeing an issue integrating with a module independent of poetry, which complains about duplication in an input requirements.txt file. But at that point, it's no longer for poetry to care about, so I think your conclusion is sufficient for resolving this issue.
