### ISSUE TITLE
Poetry export does not export local editable requirements correctly

### ISSUE THREAD

**Issue by pawelrubin** [python-poetry/poetry-plugin-export#145]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Catalina 10.15.7
- **Poetry version**: 1.1.4
- **Python version**: 3.9.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/pawelrubin/c20a783832924952dc0c0b9fa88974f0
- **Link of a [Gist](https://gist.github.com/) with the contents of your poetry.lock file**: 
https://gist.github.com/pawelrubin/19731324b4ed3b1f3d50c6634befc016
- **Link of a [Gist](https://gist.github.com/) with the contents of your example_pkg/setup.py file**: 
https://gist.github.com/pawelrubin/563bba1d591959c674c8aca81d3918ad

## Issue

Local editable packages are not exported correctly by poetry. Thus, `pip install -r requirements.txt` fails with error:
```shell
ERROR: Invalid requirement: 'example-pkg @ /Users/pawelvewd/projects/test_poetry/example_pkg' (from line 3 of requirements.txt)
Hint: It looks like a path. File 'example-pkg @ /Users/pawelvewd/projects/test_poetry/example_pkg' does not exist.
```

### Expected result
```shell
-e ./example_pkg["foo"] ; python_version >= "3.9"
```

### Current result
```shell
example-pkg @ /Users/pawelvewd/projects/test_poetry/example_pkg; python_version >= "3.9"
```

- the path should be relative IMO
- Poetry does not export `extras`
- Poetry does not export `develop = true` (editable mode)

**Comment by asaf-kali** [comment]
Took a similar to @bow:

```Makefile
freeze:
	poetry export -f requirements.txt --output requirements.txt
	sed -i '' '/my-package/d' requirements.txt
	echo "-e sub-dir/" >> requirements.txt
```

**Comment by Slanman3755** [comment]
+1 running into this as well

**Comment by fredsensibill** [comment]
I opened [a PR](https://github.com/python-poetry/poetry-plugin-export/pull/258) following @bow suggestion. Hopefully I can get a maintainer to look at it.
