### ISSUE TITLE
`index-url` and `extra-index-url` order in requirements.txt

### ISSUE THREAD

**Issue by mohsen-eng74** [python-poetry/poetry-plugin-export#169]
Hello,
I'm using Poetry (version 1.3.1) with local offline private and public Package Index Sources.
It seems that `pip` does not respect the exported `--index-url`, and `--extra-index-url` in `requirements.txt`. By trial and error, I found that the problem is related to the **order** of the URLs in the exported  `requirements.txt` file. This is the scenario:

<br />

> Scenario#1
If `--extra-index-url` comes first in the `requirements.txt` file, pip only searches for the <PUBLIC_PACKAGE_INDEX_SOURCE_URL>.
```
--extra-index-url <PRIVATE_PACKAGE_INDEX_SOURCE_URL>
--index-url <PUBLIC_PACKAGE_INDEX_SOURCE_URL>
...
```
```
pip install --no-cache-dir -r requirements.txt
**Looking in indexes: <PUBLIC_PACKAGE_INDEX_SOURCE_URL>**
```

<br />

> Scenario#2
If `--index-url ` comes first in the `requirements.txt` file, pip searches for both <PUBLIC_PACKAGE_INDEX_SOURCE_URL>, and <PRIVATE_PACKAGE_INDEX_SOURCE_URL>.
```
--index-url <PUBLIC_PACKAGE_INDEX_SOURCE_URL>
--extra-index-url <PRIVATE_PACKAGE_INDEX_SOURCE_URL>
...
```
```
pip install --no-cache-dir -r requirements.txt
**Looking in indexes: <PUBLIC_PACKAGE_INDEX_SOURCE_URL>, <PRIVATE_PACKAGE_INDEX_SOURCE_URL>**
```

<br />

Currently, the Poetry export plugin default behaviour is the same as `Scenario#1` which causes the issue.
Regards.

**Comment by dimbleby** [comment]
duplicate #149
