### ISSUE TITLE
Provide single hash and pip insall fails

### ISSUE THREAD

**Issue by mazlum** [python-poetry/poetry-plugin-export#170]
export command provides single hash for yamllint

```
yamllint==1.28.0 ; python_version >= "3.10" and python_version < "4.0" \
    --hash=sha256:9e3d8ddd16d0583214c5fdffe806c9344086721f107435f68bad990e5a88826b
```

And pip fails

```
poetry export -f requirements.txt --with dev | poetry run -- pip install -r /dev/stdin
```

![image](https://user-images.githubusercontent.com/5855630/207567575-ed42c3fa-4923-4bf0-acd9-d44f71e5b766.png)

**Comment by clintonroy** [comment]
Please always fill out the bug report, so we can avoid asking a million questions.

Please always use text in bug reports, it makes things much easier to read.

The hash is correct for the source tarball, not for the wheel.

**Comment by mazlum** [comment]
Thank you, 

But poetry creates multiple hashes for other packages.

For example
```
django==4.1.4 ; python_version >= "3.11" and python_version < "4.0" \
    --hash=sha256:0b223bfa55511f950ff741983d408d78d772351284c75e9f77d2b830b6b4d148 \
    --hash=sha256:d38a4e108d2386cb9637da66a82dc8d0733caede4c83c4afdbda78af4214211b
yamllint==1.28.0 ; python_version >= "3.11" and python_version < "4.0" \
    --hash=sha256:9e3d8ddd16d0583214c5fdffe806c9344086721f107435f68bad990e5a88826b
```

It can be seen wheel hash for Django but It does not provide for yamllint.
https://pypi.org/project/Django/#files

I think, it's about, yamllint supports py2
https://pypi.org/project/yamllint/#files

![image](https://user-images.githubusercontent.com/5855630/207586585-3518b306-97d3-48ec-9996-d776878713a5.png)

**Comment by dimbleby** [comment]
the yamllint bdist was published a month or so after the sdist, probably you have a stale cache that knows about one but not the other.

Clear your cache, re-lock, try again

**Comment by mazlum** [comment]
I tried but nothing changed

**Comment by dimbleby** [comment]
Then you either didn't clear your cache, or didn't re-lock.  Poetry simply does not behave in the way that you are claiming.

If I am wrong then a great way to progress this would be for you to provide a dockerfile that reproduces the behaviour you are seeing

**Comment by mazlum** [comment]
I think you are right.

```
# https://medium.com/swlh/alpine-slim-stretch-buster-jessie-bullseye-bookworm-what-are-the-differences-in-docker-62171ed4531d
# Choose one of these images if your code is compatible with a specific version of the Debian operating system.

FROM python:3.10.7-slim-buster

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PYTHONDONTWRITEBYTECODE=1 \
  # pip:
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # poetry:
  POETRY_VERSION=1.2.2 \
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  POETRY_HOME='/usr/local'


RUN apt-get update && apt-get upgrade -y \
  && apt-get install --no-install-recommends -y \
  curl \
  # Installing `poetry` package manager:
  # https://github.com/python-poetry/poetry
  && curl -sSL 'https://install.python-poetry.org' | python - \
  && poetry --version

# set a directory for the APP
WORKDIR /app

COPY . /app

RUN poetry export -f requirements.txt | poetry run -- pip install -r /dev/stdin
```

It works.
