### ISSUE TITLE
1.3.0 - extra labels should be normalized like package names

### ISSUE THREAD

**Issue by chargr** [python-poetry/poetry-plugin-export#181]
adding ydata-profiling to a poetry project it has a visions dependency with extra 'type-image-path':

the exports end up containing:
```
visions[type-image-path]==0.7.5
```

which causes the below pip install error when requested with 'ydata-profiling' package (or pandas-profiling)
```
AssertionError: Internal issue: Candidate is not for this requirement visions[type-image-path,type-image-path] vs visions[type-image-path]
```

this can be reproduced manually with
```
./test-3.10/bin/pip install 'ydata-profiling==4.0.0' 'visions[type-image-path]==0.7.5'
```

looking at the setup.py for visions, i see the expected name is 'type_image_path'.

converting to:
```
./test-3.10/bin/pip install 'ydata-profiling==4.0.0' 'visions[type_image_path]==0.7.5'
```

just doing a pip install of 'ydata-profiling' w/o specifying the visions dependency will correctly trigger the 'trigger_image_path' extras.

installing just visions with the dash/hyphen label, will show a warning about the bad extra name.
```
WARNING: visions 0.7.5 does not provide the extra 'type-image-path'
```

**Comment by chargr** [comment]
Cancelling this.

I see other cases where the module uses pyproject.toml with hyphens in the name and are valid.
jsonschema for example.

**Comment by dimbleby** [comment]
you forgot to close this
