### ISSUE TITLE
export saves absolute path to dependecy

### ISSUE THREAD

**Issue by currychris** [python-poetry/poetry-plugin-export#185]
- **Poetry version**: 1.3.2
- **Python version**: 3.9.13
- **OS version and name**: Windows Server 2019 Standard, Version 1809
- **pyproject.toml**: [gist](https://gist.github.com/currychris/1199f3d277d352d08ea84d78ddab8fea)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

As you can see in my pyproject.toml, I have a dependency that is referenced by a file path:
`neoapi = {file = "libs/neoapi-1.2.0-cp39-cp39-win_amd64.whl"}`.
When runnning
`poetry export --no-hashes -f requirements.txt -o requirements.txt`
the corresponding line yields:
`neoapi @ file:///C:/blank/neoapi-1.2.0-cp39-cp39-win_amd64.whl ; python_version >= "3.9" and python_full_version < "3.10.0" and python_full_version != "3.9.7"`.

I think absolute paths make no sense here. If this is intended, please add an option to instead use relative paths.

**Comment by neersighted** [comment]
See https://github.com/python-poetry/poetry/issues/5273; relative paths are not allowed in Python dependency specifications.

**Comment by dimbleby** [comment]
while that's true, requirements.txt is more relaxed / less well defined.

eg among the examples given at https://pip.pypa.io/en/stable/reference/requirements-file-format/#example we find
```
# It is possible to refer to specific local distribution paths.
./downloads/numpy-1.9.2-cp34-none-win32.whl
```
Not that I've any intention of doing anything with this one myself, but I don't think it's a completely wrong ask.

(It likely is one of those things where: if the raiser wants it, then they need to contribute it themselves!)
