### ISSUE TITLE
Poetry export hangs with path dependencies

### ISSUE THREAD

**Issue by JasperJuergensen** [python-poetry/poetry-plugin-export#200]
I have three local packages:
- package1 (has some optional package and an extra)
- package2 (depends on package1 on with some extra dependency)
- package3 (depends on package2)

Each dependency is referenced as a path dependency.
You can find this setup at https://github.com/JasperJuergensen/poetry-export-bug

If I now go to package3 and run `poetry export -vvv -f requirements.txt -o requirements.txt --without-hashes --only main`, the command hangs forever:
```
~/package3$ poetry export -vvv -f requirements.txt -o requirements.txt --without-hashes --only main
Loading configuration file /home/jasper/.config/pypoetry/config.toml
Source (poetry-lockfile): 1 packages found for package2 *
^C
```
If I run the export command in package1 or package2, there are no problems and the export works as expected.

This bug was introduced with poetry >=1.4.0. With poetry 1.3.2 it works without any problems.
I use python 3.8.15

If I change the extra package to something different (like requests 1.29.*), the export command works as expected, so it's probably something with the dependencies from alembic.

**Comment by JasperJuergensen** [comment]
I am not 100% sure, how you set up your testing environment, but when I cloned the poetry-plugin-export and installed everything, it installs poetry 1.3.0, where the problem does not occur.

When I install the latest dev version of poetry itself with git (`Poetry (version 1.5.0.dev0)`  VERSION: `https://github.com/python-poetry/poetry.git@master`) the problem still exists.

Even if I then install the current master branch of the export plugin into the latest dev version of poetry, it does not solve the problem. So I would not consider this fixed with something that came onto the main branch.

**Comment by dimbleby** [comment]
it's fixed by the main branch of poetry-core, please close

**Comment by JasperJuergensen** [comment]
You're right, thanks for the info. I will then just wait for the next poetry release with an updated poetry-core version.
