### ISSUE TITLE
Update urllib3

### ISSUE THREAD

**Issue by tranvannhat** [python-poetry/poetry-plugin-export#238]
The `urllib3` package has the following compatible candidates `[Package('urllib3', '1.26.17')]`;  but, the exporter dependency walker previously elected `urllib3 (2.0.6)` which is not compatible with the dependency `urllib3 (>=1.25.4,<1.27)`. Please contribute to `poetry-plugin-export` to solve this problem.

**Comment by radoering** [comment]
duplicate: #183

**Comment by tranvannhat** [comment]
duplicate but no solution and update?

**Comment by radoering** [comment]
This issue is a duplicate of an open issue and yes, usually an issue is open because it has not been resolved yet. However, we only need one open issue per bug.
