### ISSUE TITLE
[1.6.0] Issue with git sub-dependency resolution

### ISSUE THREAD

**Issue by bmika1** [python-poetry/poetry-plugin-export#245]
Hi, 

I have a setup where both my library and its dependency both require the same Poetry dependency via a git repository. 
Following the 1.6.0 update, the main dependency is resolved to the latest commit as expected. However, the sub-dependency does not resolve in the same manner, leading to an inconsistency that generates the error described below:

```
#14 26.15 ERROR: Cannot install -r /app/requirements.txt (line 9) and certain-library 0.4.2 (from git+https://github.com/***/certain-library.git@f44ef1ae7046c22850332fde09a30197401fe50a) because these package versions have conflicting dependencies.
#14 26.15 
#14 26.15 The conflict is caused by:
#14 26.15     The user requested certain-library 0.4.2 (from git+https://github.com/***/certain-library.git@f44ef1ae7046c22850332fde09a30197401fe50a)
#14 26.15     another-library 0.1.7 depends on certain-library 0.4.2 (from git+https://github.com/***/certain-library.git@main)
```

Would it be possible to introduce an option in poetry-plugin-export's resolution mechanism that prevents the automatic resolution of commit hashes for git dependencies, thereby allowing users to maintain the pre-1.6.0 behavior when needed?

Looking forward to any suggestions or guidance on this matter.

**Comment by dimbleby** [comment]
duplicate #244 - same solution presumably - please close
