### ISSUE TITLE
1.1.2: regression with poetry export when using python version constraints.

### ISSUE THREAD

**Issue by oncleben31** [python-poetry/poetry-plugin-export#30]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.5
- **Poetry version**: 1.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
I have notice a regression compared to poetry 1.0.10 in the following case:
 - I add package dependency with a python version constraint ("typing-extensions")
 - I add a development dependency having the same sub-dependency with no python version constraint ("black").

The command `poetry export` give a wrong result with poetry 1.1.2 (it's OK with 1.0.10)

### How to reproduce: 

``` shell
poetry new example
cd example
sed -i '/^python = /s/3.8/3.7/' pyproject.toml
poetry add --python="<3.8" typing-extensions
poetry export -f requirements.txt | grep typing
poetry add --dev black
poetry export -f requirements.txt | grep typing
```

Output for Poetry 1.0.10 (Python 3.8.6):

```
...
typing-extensions==3.7.4.3; python_version < "3.8" \
...
typing-extensions==3.7.4.3 \
```

Output for Poetry 1.1.2 (Python 3.8.6):

```
...
typing-extensions==3.7.4.3; python_version < "3.8" \
...
typing-extensions==3.7.4.3; python_version < "3.8" \
```

**Comment by dimbleby** [comment]
original bug report seems not to be a regression but a fix: adding a dev-dependency should not affect the export of non-dev packages.  If we instead `export --dev` then the marker is relaxed as expected.

Example at https://github.com/python-poetry/poetry-plugin-export/issues/30#issuecomment-721439552 also works fine today: `export` gives
```
zipp==3.6.0 ; python_version >= "3.6" and python_version < "3.7"
```
and `export --dev` gives
```
zipp==3.6.0 ; python_version >= "3.6" and python_version < "3.8"
``` 

This is fixed.
