### ISSUE TITLE
`Poetry export` should use per-package --index-url instead of single --extra-index-url

### ISSUE THREAD

**Issue by jaklan** [python-poetry/poetry-plugin-export#37]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave 10.14.6
- **Poetry version**: 1.1.3 with python-poetry/poetry#3251 fix

## Issue

This issue is a follow-up to the problem identified in python-poetry/poetry#3238:

> But... there's one more thing. I've also run:
> `poetry@3251 export -f requirements.txt -o requirements.txt --without-hashes --with-credentials`
> and the first line of the output file is:
> `--extra-index-url http://repository.intranet.foobar.com/artifactory/api/pypi/pypi-virtual/simple`
> 
> When using `default = true` we get then:
> `--index-url http://repository.intranet.foobar.com/artifactory/api/pypi/pypi-virtual/simple`
> 
> At first sight it seems okay, but we have to remember about the issue with pip and `--extra-index-url`:
> https://pydist.com/blog/extra-index-url
> https://github.com/pypa/pip/issues/5045
> I assume it's already handled by Poetry itself, but to make it error-prone when exporting the `requirements.txt` file imho we should also keep the approach of specifying individual index per each package, e.g.:
> `--index-url http://repository.intranet.foobar.com/artifactory/api/pypi/pypi-virtual/simple anyconfig==0.9.11`
> 
> PS Of course there should be also `--trusted-host` flag in any of these scenarios due to `http`, but there was another PR for that, afair - already merged, just not released yet.

@abn has already confirmed the validity of the issue, but also provided one concern:

> @jaklan appreciate the input on that. I'd suggest we raise that as a new issue. I agree that a per package index is better for the extra-index case. One worry, however, is that people seem to be attached to the current export format because some do text processing of the output it for various reasons.

So we also have to consider how to introduce such a change not to break any existing workflows.

**Comment by henrytseng** [comment]
It seems that settings from `pyproject.toml` aren't getting pulled into `requirements.txt` either.  

```
[[tool.poetry.source]]
name = "myprivate"
url = "https://myprivate/simple/"
default = true

[[tool.poetry.source]]
name = "default"
url = "https://pypi.org/simple"
secondary = true
```

Should create a `requirements.txt` with 

```
--index-url https://myprivate/simple
--extra-index-url https://pypi.org/simple
```

**Comment by neersighted** [comment]
Closing as wontfix given that this is a limitation of the format and not up to Poetry. @henrytseng's issue is different and already fixed.
