### ISSUE TITLE
Poetry export creates a virtualenv

### ISSUE THREAD

**Issue by touilleMan** [python-poetry/poetry-plugin-export#78]
When running from outside of a virtualenv, `poetry export` will create a virtualenv before running the command.
This has two issues:
- creating a virtual env is slow and makes the command leaves behind unnecessary resources
- creating a virtual env prints `Creating virtualenv ...` to stdout, which means it not possible to use the command's stdout to put the output in a arbitrary location (see #77 )

On top of that creating the virtualenv is not needed for this command (I've tried with `poetry config --local virtualenvs.create true` and it works as expected)

**Comment by dimbleby** [comment]
The `ExportCommand` used to be a mere `Command` but now it is an `InstallerCommand`, which in turn is an `EnvCommand`.

I believe that it was made an `InstallerCommand` so that it had access to group dependency options, but it didn't really want to be an `EnvCommand`.

**Comment by HansBambel** [comment]
Using Poetry v1.2.0 this produces an error also when virtualenvs.create is disabled:

Building in Docker I received an error when running the following command:
`RUN poetry export -f requirements.txt | pip install -r /dev/stdin`

Error:
```
RUN poetry export -f requirements.txt | pip install -r /dev/stdin:
#0 26.79 ERROR: Invalid requirement: 'Skipping virtualenv creation, as specified in config file.' (from line 1 of /dev/stdin)
```

I am assuming that #106 fixes this as well

**Comment by dimbleby** [comment]
meanwhile send the output to file `--output requirements.txt` and use that, or (I haven't tested) `--quiet` might do the trick

**Comment by HansBambel** [comment]
As a workaround I did the following:
```
RUN poetry export -f requirements.txt --output requirements.txt
RUN pip install -r requirements.txt
```
