### ISSUE TITLE
export fails to include hashes of some requirements

### ISSUE THREAD

**Issue by shai4lt** [python-poetry/poetry-plugin-export#90]
I created an empty project, ran `poetry add s3fs`, and export created a broken file. 
https://gist.github.com/shai4lt/c5306a9c2221203c7368532c6951814a

(I should probably note that, having looked now, the packages missing hashes seem to miss them already in the lock file, so maybe export is not the culprit -- but export is where it causes issues.

poetry 1.2.0b2 with the export plugin (AFAICT poetry 1.1.13 and 1.1.14 behave the same)

**Comment by dimbleby** [comment]
as you correctly note, this is a problem with poetry and not with this plugin, so the issue is in the wrong repository

But anyway, it's fixed in 1.1.14 and 1.2.0b3.  You may need to clear your cache to prove the point.

Please close

**Comment by mkuijn-cb** [comment]
I'm sorry, but this happens in a Docker container where there is no cache. I'll post a minimum (non)working example in a bit.

**Comment by shai4lt** [comment]
I can confirm that after clearing the cache and using poetry 1.1.14 to both lock and export, the resulting lock files has hashes, and so does the exported `requirements.txt` file; and further, installing from this `requirements.txt` file works.

@mkuijn-cb I'm guessing your case is somehow different, and if so deserves its own issue.

**Comment by mkuijn-cb** [comment]
@shai4lt thank you for your comment, it brought clarity to the issue. I had neglected to `rm` the lock file, now it works.
